Add record limitation
MapColonies/automation-kit pull request #20
Opened 2024-06-13 12:21 UTC by shyeavr

add get_folder_last_modified_content for the swap update test validation process

2024-06-13 13:46 UTC, dannysigalovich requested changes

2024-06-13 13:46 UTC, dannysigalovich commented on mc_automation_tools/base_requests.py
>      if not header:
if headers is None ... then do it

2024-06-13 13:46 UTC, dannysigalovich commented on mc_automation_tools/base_requests.py
> +def send_post_request(url, body=None, header=None, params=None):
Where is the requests.post ? you are not sending post request i dont see it

2024-06-13 13:46 UTC, dannysigalovich commented on setup.py
> +# import setuptools
remove dead code.

2024-06-13 13:46 UTC, dannysigalovich commented on mc_automation_tools/validators/mapproxy_validator.py
>          links = self.extract_from_pycsw(pycsw_records)
you can use "items" maybe better 
maybe like this 
 for product_type, product_links in links.items():
        for li, link_value in product_links.items():
           if li in ["WMS", "WMTS_KVP"]:
                links[product_type][li] += f"&token={token}"
            elif li == "WMTS_BASE":
                links[product_type][li] += f"/{product_id}-{product_type}"

2024-06-13 13:46 UTC, dannysigalovich commented on mc_automation_tools/base_requests.py
>      try:
Where is the exception ? Except requests.RequestException as e: 
like this ? 
 except requests.RequestException as e:
        _log.error("Request failed: %s", str(e))
        raise

2024-06-16 13:44 UTC, shyeavr reviewed
done

2024-06-16 13:44 UTC, shyeavr commented on mc_automation_tools/base_requests.py
> +def send_post_request(url, body=None, header=None, params=None):
solve

2024-06-17 10:28 UTC, merged